# ==============================
# Cloud Build pipeline for GKE Multi-Env Deploy
# Using Cloud Deploy (Dev → Stage → Prod)
# ==============================

substitutions:
  _REGION: asia-south1
  _REPO: sample-repo
  _IMAGE: app
  _PIPELINE: sample-pipeline

steps:
# 1️⃣ Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
    - 'build'
    - '-t'
    - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_IMAGE:$SHORT_SHA'
    - './app'

# 2️⃣ Push image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
    - 'push'
    - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_IMAGE:$SHORT_SHA'

# 3️⃣ Create a Cloud Deploy release (auto-triggers deployment)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: Deploy
  entrypoint: bash
  args:
    - '-c'
    - |
      echo "🚀 Creating Cloud Deploy release..."
      gcloud deploy releases create release-$(date +%Y%m%d-%H%M%S)
