apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: sample-pipeline
  labels:
    environment: multi-env
description: "Dev → Stage → Prod pipeline with approvals and rollout"

source:
  # This FQRN is now confirmed to be correct for your 2nd gen connection.
  gitRepositoryLink: projects/innate-vigil-472406-q8/locations/asia-south1/connections/multi-env-gke-deploy/gitRepositoryLinks/Multi-Env-Deployment-GKE-using-CloudBuild-CloudDeploy

serialPipeline:
  stages:
    - targetId: dev
      profiles: ["dev"]

    - targetId: stage
      profiles: ["stage"]
      strategy:
        standard:
          verify: true
      # Correct Indentation: 'approval' is a direct child of the stage
      approval: 
        required: true

    - targetId: prod
      profiles: ["prod"]
      strategy:
        standard:
          verify: true
      # Correct Indentation: 'approval' is a direct child of the stage
      approval: 
        required: true
