apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: sample-pipeline
  labels:
    environment: multi-env
description: "Dev → Stage → Prod pipeline with approvals and rollout"

serialPipeline:
  stages:
    - targetId: dev
      profiles: ["dev"]

    - targetId: stage
      profiles: ["stage"]
      strategy:
        standard:
          verify: true
      approval:
        required: true

    - targetId: prod
      profiles: ["prod"]
      strategy:
        standard:
          verify: true
      approval:
        required: true
