# ==============================
# Cloud Build pipeline for GKE Multi-Env Deploy
# Using Cloud Deploy (Dev → Stage → Prod)
# ==============================

substitutions:
  _PROJECT_ID: innate-vigil-472406-q8
  _REGION: asia-south1
  _GIT_REPO: projects/innate-vigil-472406-q8/locations/asia-south1/connections/multi-env-gke-deploy/gitRepositoryLinks/Multi-Env-Deployment-GKE-using-CloudBuild-CloudDeploy
  _AR_REPO: sample-repo
  _IMAGE: my-app
  _PIPELINE: sample-pipeline
  _BUILD_ID: rel-${SHORT_SHA}

options:
  logging: CLOUD_LOGGING_ONLY

steps:
# Step 1️⃣: Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
    [
      'build', '-t',
      '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_AR_REPO/$_IMAGE:${_BUILD_ID}',
      './app'
    ]

# Step 2️⃣: Push Docker image
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
    [
      'push',
      '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_AR_REPO/$_IMAGE:${_BUILD_ID}'
    ]

# Step 3️⃣: Apply Cloud Deploy configuration (optional)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  id: Apply
  entrypoint: 'gcloud'
  args:
    [
      'deploy', 'apply',
      '--file=clouddeploy.yaml',
      '--region=$_REGION',
      '--project=$_PROJECT_ID'
    ]

# Step 4️⃣: Wait for targets to propagate
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  id: Wait
  entrypoint: 'bash'
  args:
    [
      '-c',
      'echo "⏳ Waiting for Cloud Deploy targets to propagate..." && sleep 30'
    ]

# Step 5️⃣: Create Cloud Deploy release
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  id: Release
  entrypoint: 'gcloud'
  args:
    [
      'deploy', 'releases', 'create', '${_BUILD_ID}',
      '--delivery-pipeline=$_PIPELINE',
      '--region=$_REGION',
      '--images', "app=$_REGION-docker.pkg.dev/$_PROJECT_ID/$_AR_REPO/$_IMAGE:${_BUILD_ID}",
      '--project=$_PROJECT_ID'
    ]

# Step 6️⃣: Promote to Stage
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  id: Promote-Stage
  entrypoint: 'gcloud'
  args:
    [
      'deploy', 'releases', 'promote', '${_BUILD_ID}',
      '--delivery-pipeline=$_PIPELINE',
      '--to-target=stage',
      '--region=$_REGION',
      '--project=$_PROJECT_ID'
    ]

# Step 7️⃣: Promote to Prod
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  id: Promote-Prod
  entrypoint: 'gcloud'
  args:
    [
      'deploy', 'releases', 'promote', '${_BUILD_ID}',
      '--delivery-pipeline=$_PIPELINE',
      '--to-target=prod',
      '--region=$_REGION',
      '--project=$_PROJECT_ID'
    ]
