apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: sample-pipeline
  labels:
    environment: multi-env

source:
  gitRepositoryLink: projects/innate-vigil-472406-q8/locations/asia-south1/connections/multi-env-gke-deploy/gitRepositoryLinks/Multi-Env-Deployment-GKE-using-CloudBuild-CloudDeploy

description: "Dev→Stage→Prod pipeline with approvals and rollout"

serialPipeline:
  stages:
    - targetId: dev
      profiles: ["dev"]

    - targetId: stage
      profiles: ["stage"]
      strategy:
        standard:
          verify: true
      approval:
        required: true   # ✅ approval for stage

    - targetId: prod
      profiles: ["prod"]
      strategy:
