apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
  annotations:
    deploy.cloud.google.com/target-type: helm
  labels:
    environment: prod
description: "Production environment target for sample-app"
gke:
  cluster: projects/innate-vigil-472406-q8/locations/asia-south1-a/clusters/single-cluster
executionConfigs:
- usages:
    - RENDER
    - DEPLOY
    - VERIFY
  serviceAccount: "gke-node-access@innate-vigil-472406-q8.iam.gserviceaccount.com"
  artifactStorage: "gs://innate-vigil-472406-q8-deploy-artifacts"
  executionTimeout: 600s
  workerPool: projects/innate-vigil-472406-q8/locations/asia-south1/workerPools/default
custom:
  action: helm
  config:
    release: sample-app-prod
    namespace: prod
    valuesFiles:
      - charts/sample-app/values.yaml
    set:
      env: prod
      replicaCount: 3
      image.repository: asia-south1-docker.pkg.dev/innate-vigil-472406-q8/sample-repo/sample-app
