apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: "Development environment"
customTarget:
  type: helm-deployer
  customTargetConfig:
    cluster:
      name: my-gke-cluster
      location: asia-south1-a
    namespace: dev

