apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
  labels:
    environment: prod
description: "Production environment target for sample-app"
customTarget:
  type: helm-deployer
  customTargetConfig:
    cluster:
      name: single-cluster
      location: asia-south1-a
    namespace: prod
